services:
  dither-studio:
    image: ghcr.io/enelene/dither_web_app:latest
    container_name: dither_studio_app
    ports:
      - "8001:8000"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    environment:
      - DOCKER_API_VERSION=1.41
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 1 dither_studio_app
    restart: unless-stopped
